version: 2
before:
  hooks:
    - cargo install --locked cargo-zigbuild
builds:
  - builder: rust
    targets:
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu
archives:
  - formats: ["binary"]

gitea_urls:
  api: https://git.shee.sh/api/v1
  download: https://git.shee.sh
